### ISSUE TITLE
Doesn't handle null fields.

### ISSUE THREAD

**Issue by icholy** [adrianmo/go-nmea#8]
I have the following sentence:

`$GPRMC,142754.0,A,4302.539570,N,07920.379823,W,0.0,,070617,0.0,E,A*3F`

Which fails to parse with: `GPRMC decode course error:` due to the parser not handling null fields correctly. The easiest solution would be to use `0` when there's a null field, but idk if that's a good idea.

https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_MessageOverview.html

> All messages conform to the NMEA-0183 version 3.01 format. All begin with $ and end with a carriage return and a line feed. Data fields follow comma (,) delimiters and are variable in length. **Null fields still follow comma (,) delimiters, but contain no information.**

**Comment by icholy** [comment]
@adrianmo the [gpgsv](https://github.com/adrianmo/go-nmea/blob/adc20ca878e6cd52866b3c540ba8dcd077ad550a/gpgsv.go#L47-L52) parsing code checks for empty strings before parsing. Would you accept a PR adding these checks to all fields?

**Comment by adrianmo** [comment]
Good catch @icholy! 

I would definitely accept the PR with the proposed solution. Even though that will set a [zero value](https://tour.golang.org/basics/12) to those fields. 

In the future we should probably change the struct fields to pointers instead of values. That empty fields will be <nil>.

@icholy do all values in a NMEA sentence accept an empty string? Can you fix the rest of sentence types that have the same issue? Can you add a couple of tests with empty values sentences?

Thanks!

**Comment by icholy** [comment]
@adrianmo I'm pretty sure not all fields are allowed to be null, but I'm having a hard time finding explicit documentation.

**Comment by adrianmo** [comment]
@icholy OK, let's at least check for an empty string and prevent the lib from crashing.

**Comment by icholy** [comment]
@adrianmo I'm looked at the parser in https://github.com/cloudyourcar/minmea, and it just assigns zero values if the fields are null.

**Comment by adrianmo** [comment]
@icholy great - let's do the same then.
